packages:
  - apps/*
  - packages/*
allowBuilds:
  esbuild: true
  workerd: true
minimumReleaseAgeExclude:
  - miniflare@5.20260828.0-alpha
  - wrangler@4.127.1
  - '@cloudflare/workers-types@5.20260829.1'
